run:
  timeout: 5m
  tests: true
  concurrency: 4

issues:
  exclude-files:
    - ".*.gen.go"
    - ".*_test.go"
  exclude-dirs:
    - "migrations"

output:
  formats:
    - colored-line-number

linters:
  enable:
    - govet
    - revive
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - typecheck
#    - structcheck
#    - deadcode
    - gocritic
    - gofmt
    - goimports
    - bodyclose
#    - exportloopref
  disable:
    - interfacer
#    - scopelint
#    - golint
#    - varcheck
    - depguard

linters-settings:
  revive:
    severity: warning
    rules:
      - name: indent-error-flow
      - name: var-naming
        arguments: [ "camelCase" ]
