run:
  timeout: 5m
  tests: true
  concurrency: 4

issues:
  exclude-files:
    - ".*.gen.go"
    - ".*_test.go"
  exclude-dirs:
    - "migrations"

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    - govet
    - revive
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - typecheck
    #    - structcheck
    #    - deadcode
    - gocritic
    - gofmt
#    - goimports
    - bodyclose
  #    - exportloopref
  disable:
    #    - scopelint
    #    - golint
    #    - varcheck
    - depguard

linters-settings:
  revive:
    severity: warning
    rules:
      - name: indent-error-flow
      - name: var-naming
        arguments: [ [ "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XSRF", "XSS" ] ]

