version: '3.8'

services:
  test-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DATABASE_URL: postgres://test_user:test_password@test-db:5432/test_db?sslmode=disable
      JWT_SECRET: test-secret
      TOKEN_EXPIRATION_MINUTES: 60
      REFRESH_EXPIRATION_HOURS: 168
      LOG_LEVEL: info
    depends_on:
      test-db:
        condition: service_healthy
    volumes:
      - .:/app
      - go-cache:/go
    working_dir: /app

volumes:
  go-cache: 