global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'oauth2-server'
    static_configs:
      - targets: [ 'oauth2-server:8080' ]
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres:5432' ]

  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis:6379' ]
