global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'oauth2-server'
    static_configs:
      - targets: [ 'oauth2-server:8080' ]
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres:5432' ]
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
    scrape_interval: 15s
